# Generated by Django 4.2.2 on 2023-07-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_monosettings_order_book_price_book_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
