# Generated by Django 4.2.2 on 2023-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_book_price_alter_book_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=200),
        ),
    ]
