# Generated by Django 4.2.2 on 2023-07-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
